2020-11-08 12:49:26,503 ERROR: Exception on /my_tasks/chief/ [GET] [in /home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ppa/PycharmProjects/fleadert/app/main/routes.py", line 81, in render_tasks_list
    return render_template('my_tasks.html', user=query_user, tasks=tasks, title="Задачи", fig=fig, test=fig2, test1=test_fig)
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/ppa/PycharmProjects/fleadert/app/templates/my_tasks.html", line 71, in template
    {{ test 1 }}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'integer'
2020-11-08 12:52:38,131 INFO: App startup [in /home/ppa/PycharmProjects/fleadert/app/__init__.py:54]
2020-11-08 12:52:41,519 ERROR: Exception on /my_tasks/chief/ [GET] [in /home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ppa/PycharmProjects/fleadert/app/main/routes.py", line 81, in render_tasks_list
    return render_template('my_tasks.html', user=query_user, tasks=tasks, title="Задачи", fig=fig, test=fig2, test1=test_fig)
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/ppa/PycharmProjects/fleadert/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/ppa/PycharmProjects/fleadert/app/templates/my_tasks.html", line 71, in template
    {{ test 1 }}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'integer'
2020-11-08 12:53:23,866 INFO: App startup [in /home/ppa/PycharmProjects/fleadert/app/__init__.py:54]
2020-11-08 13:39:47,150 INFO: App startup [in /home/ppa/PycharmProjects/fleadert/app/__init__.py:54]
2020-11-08 13:40:24,697 INFO: App startup [in /home/ppa/PycharmProjects/fleadert/app/__init__.py:54]
2020-11-08 13:40:59,478 INFO: App startup [in /home/ppa/PycharmProjects/fleadert/app/__init__.py:54]
2020-11-08 13:50:47,741 INFO: App startup [in /home/ppa/PycharmProjects/fleadert/app/__init__.py:54]
